- name: Cloner le dépôt impacket
  git:
    repo: https://github.com/SecureAuthCorp/impacket.git
    dest: /opt/impacket
    force: yes

  become: true
  become_method: sudo

- name: Changer le répertoire de travail
  shell: cd /opt/impacket

- name: Installer impacket
  pip:
    name: .
    editable: yes
    state: present
  args:
    chdir: /opt/impacket
  become: true
  become_method: sudo

- name: Installer les dépendances
  pip:
    requirements: /opt/impacket/requirements.txt
    state: present
  args:
    chdir: /opt/impacket
  when: requirements_file.stat.exists
  failed_when: false
