- name: "Git for package manager of tmux"
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"
    version: master

  ignore_errors: true

- name: "Check if tpm is already cloned"
  stat:
    path: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"
  
  register: tpm_check


- name: "Copy tmux Config"
  copy:
    src: "{{ role_path}}/files/.tmux.conf"
    dest: "{{ ansible_env.HOME }}"

- name: "Source tmux Config"
  shell: tmux source-file {{ ansible_env.HOME }}/.tmux.conf

- name: "Install plugins"
  shell: "{{ ansible_env.HOME }}/.tmux/plugins/tpm/bin/install_plugins"

