- name: "Dependance for zsh"
  apt:
    name:
      - zsh
      - fzf
      - git
      - neovim

    state: present
  become: true
  become_method: sudo


- name: "Dependance for tmux"
  apt:
    name: tmux

    state: present

  become: true
  become_method: sudo

- name: "Dependance for all language"
  apt:
    name:
      - python3
      - python3-pip
      - python3-venv
      - pipx
      - golang-go

    state: present

  become: true
  become_method: sudo
