- name: "Install Tmux"
  apt:
    name: tmux
    state: present

  become: true
  become_method: sudo

- name: "Copy Tmux Config"
  copy:
    src: "{{ role_path }}/files/.tmux.conf"
    dest: "{{ ansible_env.HOME }}"

- name: Configure bash to start tmux automatically
  lineinfile:
    path: ~/.bashrc
    insertafter: EOF
    line: |
      # Start tmux automatically if not already in a tmux session
      if [ -z "$TMUX" ]; then
          tmux
      fi

  when: zshrc_file.stat.exists

- name: Configure zsh to start tmux automatically
  lineinfile:
    path: ~/.zshrc
    insertafter: EOF
    line: |
      # Start tmux automatically if not already in a tmux session
      if [ -z "$TMUX" ]; then
          tmux
      fi
  when: zshrc_file.stat.exists
