- name: Ensure zsh is installed
  apt:
    name: zsh
    state: present

- name: Change default shell to zsh for current user
  user:
    name: "{{ ansible_env.USER }}"
    shell: /usr/bin/zsh

- name: Check if .zshrc exists
  stat:
    path: ~/.zshrc
  register: zshrc_file

- name: Copy zsh configuration
  copy:
    src: "{{ role_path }}/files/.zshrc"
    dest: "{{ ansible_env.HOME }}"

